    $(document).ready(function(){
        $('.dtbtn:nth-of-type(1)').click(function(){
            $('#detail').fadeIn();
            $('#review').hide();
            $('#qna').hide();
            $('#deliver').hide();
            $('#change').hide();
            $('.dtbtn').removeClass('bold');
            $(this).addClass('bold');
        });

        $('.dtbtn:nth-of-type(2)').click(function(){
            $('#review').fadeIn();
            $('#detail').hide();
            $('#qna').hide();
            $('#deliver').hide();
            $('#change').hide();
            $('.dtbtn').removeClass('bold');
            $(this).addClass('bold');
        });
        $('.dtbtn:nth-of-type(3)').click(function(){
            $('#qna').fadeIn();
            $('#detail').hide();
            $('#review').hide();
            $('#deliver').hide();
            $('#change').hide();
            $('.dtbtn').removeClass('bold');
            $(this).addClass('bold');
        });
        $('.dtbtn:nth-of-type(4)').click(function(){
            $('#deliver').fadeIn();
            $('#detail').hide();
            $('#review').hide();
            $('#qna').hide();
            $('#change').hide();
            $('.dtbtn').removeClass('bold');
            $(this).addClass('bold');
        });
        $('.dtbtn:nth-of-type(5)').click(function(){
            $('#change').fadeIn();
            $('#detail').hide();
            $('#review').hide();
            $('#qna').hide();
            $('#deliver').hide();
            $('.dtbtn').removeClass('bold');
            $(this).addClass('bold');
        });
    })